name = "CopernicusData"
uuid = "38a357ab-94f1-4047-92d1-029f77111eef"
authors = ["Vincent Levasseur <vince.levasseur@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
